name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  ITCH_USERNAME: casmo
  ITCH_GAME_ID: 4705273

jobs:
  deploy:
    name: Deploy - Itch.io ${{ matrix.template }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - webgl
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set Version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          else
            echo "version=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi
      - name: Upload ${{ matrix.preset }} to itch.io project
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_API_KEY}}
          gameData: /dist
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ env.version }}